### ISSUE TITLE
Anpassungen für Demokratiecafes

### ISSUE THREAD

**Issue by mrothauer** [anstiftung/mapped-repair-events#116]
**todo**

**nach Deploy auf www.demokratiecafe.de**
* [x] Cronjobs auf all-inkl.com umstellen von test auf www

**done** #124 
* [x] Grafische Anpassungen (z.B. geänderte Farben)
* [x] Matomo einbinden (live)
* [x] Favicon
* [x] Kategorien anpassen (inkl. Grafiken)
* [x] Home: andere Toggle-Bilder
* [x] Home: andere Slider-Bilder
* [x] Platzhalter-Logo anpassen
* [x] Home: letzte Zeile ausblenden
* [x] Geändertes Logo einbinden
* [x] Übersetzungen an CakePHP4 anpassen (Stand von CakePHP2)
* [x] Strings anpassen und systemweit verwenden

**done** #118
* [x] Cronjobs einrichten (Datenbank-Backup)
* [x] Domain einrichten: test.demokratiecafe.de
* [x] Hauptmenü: Netzwerktreffen weg / auch Kategorie 2 in Blog-Formular weg
* [x] Hauptmenü: FB und Twitter ausblenden
* [x] Cronjobs für UserUploads anpassen und einrichten
* [x] Datenbank-Backup-File umbenennen mit Domain als Präfix
* [x] statisticsEnabled: false (Meine Termine: Laufzettel weg (in Überschrift und 1. Spalte der Tabelle mit Link zu "Laufzettel erstellen"), Statistik-Feld in Initiativen-Formular weg, Download-Statistik-Link weg, Admin: Menüpunkte Laufzettel / Marken / ORDS ausblenden
* [x] Widget-Seite: Karte und Statistik weggeben
* [x] Widgets zu Widget in Footer
* [x] Unterkategorien löschen (Datenbank)
* [x] Hauptmenü: Aktive und Kenntnisse & Interessen ausblenden / Aktive und Kenntnisse und Reparaturwissen auch nicht über url aufrufen
* [x] Deploy-Skript Optimierungen (keine tmp-domain, installations outsourced)
* [x] onlineEventsEnabled: false ("Termin findet nur als Online-Reparaturcafé über Videokonferenz statt" weg - auch in Suche Häkchen weg, Bild auf Home-Karte weg, Feld in Termin-Formular weg
* [x] SMTP: Email-Adresse: info@demokratiecafe.de anlegen und als Absender-Adresse einbinden
* [x] Error-Mail-Betreff anpassen: "ErrorLog RepIni"
* [x] Matomo umziehen (stats.anstiftung.de) - stats raus aus deploy-skript
