### ISSUE TITLE
Upgrade to CakePHP 5

### ISSUE THREAD

**Issue by mrothauer** [anstiftung/mapped-repair-events#134]
https://book.cakephp.org/5/en/appendices/5-0-upgrade-guide.html
https://book.cakephp.org/5/en/appendices/5-0-migration-guide.html

cakephp-feed: Until then use ^3.0.0@RC as version constraint.

upgrade tool:
`rep-php bash ./upgrade/bin/cake upgrade rector --rules cakephp50 plugins/Admin/src`
`rep-php bash ./upgrade/bin/cake upgrade rector --rules cakephp50 src`
`rep-php bash ./upgrade/bin/cake upgrade rector --rules cakephp50 tests`

**todos**
* [x] feed.rss https://github.com/dereuromark/cakephp-feed/blob/master/docs/View/Rss.md
* [x] unit tests: test und dev db kommen durcheinander
* [x] ical testen
* [x] phpstan level 1
* [x] phpstan errors (dynamic properties)
* [x] :$Authentication :$AppFlash
* [x] $this->RequestHandler->renderAs($this, 'json');

** sobald fertig**
* [ ] 2.0 taggen
